### ISSUE TITLE
Noticed a few differences in colors in jsx files

### ISSUE THREAD

**Issue by shmup** [arzg/apprentice-vscode#1] opened 2022-09-02 14:25 UTC
This might be intentional, or just something we can tackle. Love that you made this, I like some things about it more than the other apprentice for vscode.

I'd gladly help resolve things if we agree for consistency. If this is a personal preference, all good! That's what forks are for hehe.

Noticed in `jsx`, the left being vscode and the right being vim.

Let me know what ya think about the differences and if we'd like it "fixed"

![image](https://user-images.githubusercontent.com/118710/188170360-ebbc2dcd-0cc2-4d59-affc-7e3f7a0810fe.png)

**Comment by lunacookies** [comment] 2022-09-02 14:39
So first off ignoring the brackets, since they are affected by VS Code’s bracket pair colourisation:

1. Vim has richer doc comment highlighting
2. Vim highlights HTML tags as _functions?_
3. Vim highlights `const` as a type

(1) is a deficiency with VS Code’s syntax highlighting, (2) is a mistake in Vim’s JSX syntax highlighting (in XML and HTML tags are in blue, not yellow) and (3) I think is questionable – isn’t `const` a keyword, and as such should be in blue?

**Comment by shmup** [comment] 2022-09-02 14:42
These are all valid points and will deserve a better answer than this one I'm going to give right now, you might be right in all accounts.

The reason I opened this ticket, my quick reply, is just that I'm experiencing that thing where code looks goofy to me (new job, new computer, and new text editor) with alternative colors. Maybe `const` "should" be blue, but it's been purple for a long time for me on the other computer.

Curious what @romainl would say heheh. They also work with JSX

**Comment by lunacookies** [comment] 2022-09-02 15:17
I’m curious, too; it’s bothered me for a long time that JS keywords like `const`, `function`, etc are highlighted as types instead of keywords. @romainl is it your intent to have Apprentice highlight code ‘logically’ according to what every highlight group represents in the code, or rather are you just following the Vim defaults?

**Comment by romainl** [comment] 2022-09-03 07:55
Visual Studio Code? What did you drag me into?

As you know, in Vim, all filetype-specific highlight groups must somehow link to one of the generic built-in ones like `Type` or `Statement`. In general, my colorschemes focus on those "core" highlight groups without being too opinionated about a specific language. There are things that matter to me, like having the `<` and the `tag` in `<tag` the same color or a couple of consistency issues, but other than that, I stick with the core groups.

If a syntax author stupidly decides that `const` is a `Type`, then it's treated as a `Type`, no questions asked. From my point of view, and as per Vim's own design, it is squarely the syntax's job to get those things right, not the colorscheme's.

It all boils down to the circumstances of the syntax author: maybe they didn't like the color of `Keyword` in the colorscheme they used when they wrote the syntax had? I have no idea but *they* decided on `Type` and, if something must be fixed, it must be fixed in the syntax script.

Also, note that `$VIMRUNTIME/syntax/javascript.vim` actually gets it right:

    syn keyword javaScriptReserved		abstract boolean byte char class const debugger double enum export extends final float goto implements import int interface long native package private protected public short static super synchronized throws transient volatile async
    [...]
    hi def link javaScriptReserved		Keyword

so the issue at hand is strictly limited to whatever "JSX"-aware [syntax script](https://github.com/pangloss/vim-javascript/blob/master/syntax/javascript.vim#L35) we choose to use instead of the built-in one.

By design, `Keyword`s in Apprentice are supposed to be blue and I believe that a port of Apprentice should keep it that way.

**Comment by lunacookies** [comment] 2022-09-04 13:57
Based on that, in order to stay faithful to Apprentice it IMO makes sense to leave things as they are, rather than matching the idiosyncrasies of specific Vim syntax scripts.

**Closed as completed by lunacookies** 2022-09-04 13:57 UTC
